version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/openjdk:21.0.6
    steps:
      - checkout

      - restore_cache:
          name: Restore Maven repo and wrapper cache
          keys:
            - mvn-cache-{{ checksum "pom.xml" }}

      - run:
          name: Install X11 libs for GUI tests
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              libxext6 \
              libxrender1 \
              libxtst6

      - run:
          name: Run Maven tests
          command: |
            ./mvnw -B test

workflows:
  test:
    jobs:
      - run-tests
